/*
        Copyright (c) openheap, uplusware
        uplusware@gmail.com
*/

#ifndef __POSIXNAME__
#define __POSIXNAME__

#define BWGATED_POSIX_PREFIX "/.BWGATED_"

#define BWGATED_POSIX_QUEUE_SUFFIX ".que"
#define BWGATED_POSIX_SEMAPHORE_SUFFIX ".sem"

#define BWGATED_GLOBAL_REJECT_LIST \
  BWGATED_POSIX_PREFIX "GLOBAL_REJECT_LIST" BWGATED_POSIX_SEMAPHORE_SUFFIX
#define BWGATED_GLOBAL_PERMIT_LIST \
  BWGATED_POSIX_PREFIX "GLOBAL_PERMIT_LIST" BWGATED_POSIX_SEMAPHORE_SUFFIX

#define BWGATED_SERVICE_LOGNAME "/var/log/bwgated/service.log"
#define BWGATED_SERVICE_LCKNAME \
  BWGATED_POSIX_PREFIX "SERVICE_LOG" BWGATED_POSIX_SEMAPHORE_SUFFIX

#endif /* __POSIXNAME__ */